'use strict';
const K={houses:'posnavi-houses-v04',sessions:'posnavi-sessions-v04',current:'posnavi-current-session-v04'};
const center=[43.0621,141.3544];
const map=L.map('map',{zoomControl:false,doubleClickZoom:false}).setView(center,17);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
const $=id=>document.getElementById(id);
const state={houses:load(K.houses,[]),sessions:load(K.sessions,[]),current:load(K.current,null),markers:new Map(),selected:null,historySession:null,suppressClickUntil:0,toastTimer:null,undo:null};
function load(k,f){try{const v=JSON.parse(localStorage.getItem(k));return v??f}catch{return f}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function uid(p='id'){return `${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmt(iso){if(!iso)return '-';return new Intl.DateTimeFormat('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(iso))}
function statusLabel(v){return({normal:'通常','no-posting':'配布不可',caution:'要注意',multi:'複数部予定'}[v]||'通常')}
function typeLabel(v){return({house:'戸建て',apartment:'集合住宅',company:'会社・店舗',other:'その他'}[v]||'その他')}
function entries(){return Object.values(state.current?.entries||{})}
function total(){return entries().reduce((a,e)=>a+Number(e.copies||0),0)}
function previousForHouse(id){for(const s of state.sessions){const e=Object.values(s.entries||{}).find(x=>x.houseId===id||x.id===id);if(e)return e}return null}
function historyForHouse(id){const out=[];for(const s of state.sessions){const e=Object.values(s.entries||{}).find(x=>x.houseId===id||x.id===id);if(e)out.push({entry:e,session:s})}return out}
function currentCopies(id){return Number(state.current?.entries?.[id]?.copies||0)}
function markerIcon(house){const cur=currentCopies(house.id),prev=previousForHouse(house.id);let cls='';if(house.status==='no-posting')cls='red';else if(house.status==='caution')cls='yellow';else if(house.status==='multi'||house.type==='company')cls='purple';else if(cur>=2)cls='blue';else if(cur===1)cls='green';const main=house.status==='no-posting'?'×':cur>0?cur:'⌂';const selected=state.selected?.type==='house'&&state.selected.id===house.id?' selected':'';return L.divIcon({className:'',html:`<div class="marker-wrap"><div class="marker-main ${cls}${selected}">${main}</div>${prev?`<span class="marker-prev">前回 ${Number(prev.copies||0)}</span>`:''}</div>`,iconSize:[38,46],iconAnchor:[19,16]})}
function spotIcon(e,history=false){const selected=state.selected?.type==='spot'&&state.selected.id===e.id?' selected':'';return L.divIcon({className:'',html:`<div class="marker-wrap ${history?'marker-history':''}"><div class="marker-main green${selected}">${Number(e.copies||0)}</div></div>`,iconSize:[38,38],iconAnchor:[19,16]})}
function clearMarkers(){state.markers.forEach(m=>m.remove());state.markers.clear()}
function render(){clearMarkers();if(state.historySession){renderHistoryMap(state.historySession)}else{for(const h of state.houses){const m=L.marker([h.lat,h.lng],{icon:markerIcon(h),keyboard:false}).addTo(map);bindMarker(m,'house',h.id,()=>tapHouse(h));state.markers.set(`h:${h.id}`,m)}if(state.current){for(const e of entries()){if(e.houseId)continue;const m=L.marker([e.lat,e.lng],{icon:spotIcon(e),keyboard:false}).addTo(map);bindMarker(m,'spot',e.id,()=>tapSpot(e.id));state.markers.set(`s:${e.id}`,m)}}}updateUI()}
function bindMarker(marker,type,id,onTap){let timer=null,long=false;const arm=ev=>{long=false;clearTimeout(timer);timer=setTimeout(()=>{long=true;state.suppressClickUntil=Date.now()+700;state.selected={type,id};render();openDetail(type,id)},550);if(ev?.originalEvent)ev.originalEvent.preventDefault()};const disarm=()=>clearTimeout(timer);marker.on('mousedown touchstart',arm);marker.on('mouseup touchend touchcancel mouseout',disarm);marker.on('click',ev=>{L.DomEvent.stopPropagation(ev);clearTimeout(timer);if(long||Date.now()<state.suppressClickUntil){long=false;return}state.selected={type,id};onTap()});marker.on('contextmenu',ev=>{L.DomEvent.stopPropagation(ev);state.selected={type,id};openDetail(type,id)})}
function tapHouse(h){if(!state.current){state.selected={type:'house',id:h.id};render();return}if(h.status==='no-posting'){showToast('この場所は配布不可です');return}const old=state.current.entries[h.id]?structuredClone(state.current.entries[h.id]):null;const next=Number(old?.copies||0)+1;state.current.entries[h.id]={id:h.id,houseId:h.id,address:h.address,lat:h.lat,lng:h.lng,copies:next,updatedAt:new Date().toISOString()};persistCurrent();showToast(`${next}部を記録`,()=>{if(old)state.current.entries[h.id]=old;else delete state.current.entries[h.id];persistCurrent()})}
function tapSpot(id){if(!state.current)return;const old=structuredClone(state.current.entries[id]);state.current.entries[id].copies=Number(old.copies||0)+1;state.current.entries[id].updatedAt=new Date().toISOString();persistCurrent();showToast(`${state.current.entries[id].copies}部を記録`,()=>{state.current.entries[id]=old;persistCurrent()})}
map.on('click',ev=>{if(!state.current||state.historySession||Date.now()<state.suppressClickUntil)return;const id=uid('spot');state.current.entries[id]={id,houseId:null,address:'地図上の配布地点',lat:ev.latlng.lat,lng:ev.latlng.lng,copies:1,updatedAt:new Date().toISOString()};state.selected={type:'spot',id};persistCurrent();showToast('1部を記録',()=>{delete state.current.entries[id];if(state.selected?.id===id)state.selected=null;persistCurrent()})});
function persistCurrent(){save(K.current,state.current);render()}
function updateUI(){const t=total();$('todayCount').textContent=`${t}部`;$('doneCount').textContent=`${entries().length}件`;$('houseCount').textContent=`${state.houses.length}件`;if(state.current){$('sessionBtn').textContent='配布終了';$('sessionBtn').classList.add('active');$('sessionStatus').textContent=`配布中｜${t}部｜${fmt(state.current.startedAt)}開始`}else{$('sessionBtn').textContent='配布開始';$('sessionBtn').classList.remove('active');$('sessionStatus').textContent=state.historySession?'履歴を地図表示中':'待機中'}$('modeBanner').hidden=!state.historySession;if(state.historySession)$('modeBanner').textContent=`${state.historySession.area||'未設定エリア'}｜${fmt(state.historySession.startedAt)}　タップで終了`}
$('sessionBtn').onclick=()=>state.current?finishSession():startSession();
function startSession(){if(state.historySession)exitHistory();state.current={id:uid('session'),area:'未設定エリア',flyer:'',memo:'',startedAt:new Date().toISOString(),endedAt:null,entries:{}};save(K.current,state.current);render();showToast('配布を開始しました')}
function finishSession(){const t=total();if(!confirm(`配布を終了しますか？\n配布部数：${t}部`))return;const s={...state.current,endedAt:new Date().toISOString(),totalCopies:t,visitedCount:entries().length};state.sessions.unshift(s);save(K.sessions,state.sessions);state.current=null;localStorage.removeItem(K.current);state.selected=null;showToast('配布記録を保存しました');render()}
$('clearCurrentBtn').onclick=()=>{if(!state.current){showToast('配布中の記録はありません');return}if(!entries().length){showToast('消す記録はありません');return}if(!confirm('今回の配布記録を全部消しますか？\n住宅マスターと過去の履歴は残ります。'))return;state.current.entries={};state.selected=null;persistCurrent();showToast('今回の記録を全部消しました')};
function showToast(text,undoFn=null){clearTimeout(state.toastTimer);state.undo=undoFn;$('toastText').textContent=text;$('undoBtn').hidden=!undoFn;$('toast').hidden=false;state.toastTimer=setTimeout(hideToast,3000)}
function hideToast(){$('toast').hidden=true;$('undoBtn').hidden=true;state.undo=null}
$('undoBtn').onclick=()=>{const fn=state.undo;hideToast();if(fn)fn()};
function openSheet(title,html){$('sheetTitle').textContent=title;$('sheetBody').innerHTML=html;$('backdrop').hidden=false;$('sheet').hidden=false}
function closeSheet(){$('backdrop').hidden=true;$('sheet').hidden=true}
$('closeSheet').onclick=closeSheet;$('backdrop').onclick=closeSheet;
$('moreFab').onclick=()=>{if(state.selected&&!state.historySession)openDetail(state.selected.type,state.selected.id);else openMainMenu()};
function openMainMenu(){openSheet('メニュー',`<div class="menu-list"><button id="menuRegister">＋ 住宅を事前登録</button><button id="menuHistory">▣ 配布履歴を地図で見る</button><button id="menuSearch">⌕ 住所検索</button>${state.historySession?'<button id="menuExitHistory">履歴表示を終了</button>':''}</div>`);$('menuRegister').onclick=()=>openHouseForm();$('menuHistory').onclick=openHistoryList;$('menuSearch').onclick=openSearch;if($('menuExitHistory'))$('menuExitHistory').onclick=exitHistory}
function openDetail(type,id){if(type==='house'){const h=state.houses.find(x=>x.id===id);if(!h)return;const cur=currentCopies(id),hist=historyForHouse(id),prev=hist[0];openSheet('物件詳細',`<dl class="detail-grid"><dt>住所</dt><dd>${esc(h.address||'未入力')}</dd><dt>今回</dt><dd>${cur}部</dd><dt>前回</dt><dd>${prev?`${prev.entry.copies}部（${fmt(prev.session.startedAt)}）`:'記録なし'}</dd><dt>基本部数</dt><dd>${h.defaultCopies||1}部</dd><dt>区分</dt><dd>${typeLabel(h.type)}</dd><dt>状態</dt><dd>${statusLabel(h.status)}</dd><dt>メモ</dt><dd>${esc(h.memo||'-')}</dd></dl><div class="action-grid">${cur?'<button class="action-btn danger" id="clearPlace">今回分を全部消す</button>':'<button class="action-btn" id="mapBack">地図へ戻る</button>'}<button class="action-btn primary" id="editHouse">編集</button></div><div class="history-list">${hist.length?hist.slice(0,8).map(x=>`<div class="history-item"><strong>${x.entry.copies}部</strong><small>${fmt(x.session.startedAt)}｜${esc(x.session.area||'未設定')}</small></div>`).join(''):'<p class="empty">履歴はまだありません</p>'}</div>`);if($('clearPlace'))$('clearPlace').onclick=()=>{if(!confirm('この場所の今回分を全部消しますか？'))return;delete state.current.entries[id];closeSheet();persistCurrent()};if($('mapBack'))$('mapBack').onclick=closeSheet;$('editHouse').onclick=()=>openHouseForm(h)}else{const e=state.current?.entries?.[id];if(!e)return;openSheet('配布地点の詳細',`<dl class="detail-grid"><dt>場所</dt><dd>${esc(e.address)}</dd><dt>今回</dt><dd>${e.copies}部</dd><dt>記録時刻</dt><dd>${fmt(e.updatedAt)}</dd></dl><div class="action-grid"><button class="action-btn danger" id="deleteSpot">今回分を全部消す</button><button class="action-btn primary" id="registerSpot">住宅として登録</button></div>`);$('deleteSpot').onclick=()=>{if(!confirm('この場所の今回分を全部消しますか？'))return;delete state.current.entries[id];state.selected=null;closeSheet();persistCurrent()};$('registerSpot').onclick=()=>openHouseForm({address:'',lat:e.lat,lng:e.lng,defaultCopies:e.copies,type:'house',status:'normal',memo:''})}}
function openHouseForm(h=null){const c=map.getCenter(),x=h||{id:'',address:'',lat:c.lat,lng:c.lng,defaultCopies:1,type:'house',status:'normal',memo:''};openSheet(h?.id?'住宅情報を編集':'住宅を事前登録',`<form id="houseForm"><label>住所・建物名<input id="fAddress" value="${esc(x.address||'')}" placeholder="例：福住1条1丁目 ○○マンション"></label><div class="two-col"><label>緯度<input id="fLat" type="number" step="any" value="${x.lat}"></label><label>経度<input id="fLng" type="number" step="any" value="${x.lng}"></label></div><label>基本部数<input id="fCopies" type="number" min="0" value="${x.defaultCopies??1}"></label><label>区分<select id="fType"><option value="house">戸建て</option><option value="apartment">集合住宅</option><option value="company">会社・店舗</option><option value="other">その他</option></select></label><label>状態<select id="fStatus"><option value="normal">通常</option><option value="no-posting">配布不可</option><option value="caution">要注意</option><option value="multi">複数部予定</option></select></label><label>メモ<textarea id="fMemo" placeholder="例：チラシお断り、受付に3部">${esc(x.memo||'')}</textarea></label><button class="action-btn primary" type="submit">保存</button>${h?.id?'<button class="action-btn danger" type="button" id="deleteHouse" style="margin-top:10px">この住宅を削除</button>':''}</form>`);$('fType').value=x.type||'house';$('fStatus').value=x.status||'normal';$('houseForm').onsubmit=ev=>{ev.preventDefault();const item={id:h?.id||uid('house'),address:$('fAddress').value.trim(),lat:Number($('fLat').value),lng:Number($('fLng').value),defaultCopies:Number($('fCopies').value||0),type:$('fType').value,status:$('fStatus').value,memo:$('fMemo').value.trim(),updatedAt:new Date().toISOString()};const i=state.houses.findIndex(y=>y.id===item.id);if(i>=0)state.houses[i]=item;else state.houses.push(item);save(K.houses,state.houses);state.selected={type:'house',id:item.id};closeSheet();render();showToast('住宅情報を保存しました')};if($('deleteHouse'))$('deleteHouse').onclick=()=>{if(!confirm('この住宅情報を削除しますか？'))return;state.houses=state.houses.filter(y=>y.id!==h.id);save(K.houses,state.houses);state.selected=null;closeSheet();render();showToast('住宅情報を削除しました')}}
function openHistoryList(){openSheet('配布履歴',state.sessions.length?`<div class="history-list">${state.sessions.map(s=>`<button class="history-item" data-session="${s.id}"><strong>${s.totalCopies??Object.values(s.entries||{}).reduce((a,e)=>a+Number(e.copies||0),0)}部・${s.visitedCount??Object.keys(s.entries||{}).length}件</strong><small>${fmt(s.startedAt)}〜${fmt(s.endedAt)}｜${esc(s.area||'未設定エリア')}</small></button>`).join('')}</div>`:'<p class="empty">配布履歴はまだありません</p>');document.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>showHistoryOnMap(b.dataset.session))}
function showHistoryOnMap(id){const s=state.sessions.find(x=>x.id===id);if(!s)return;state.historySession=s;state.selected=null;closeSheet();render();const pts=Object.values(s.entries||{}).filter(e=>Number.isFinite(e.lat)&&Number.isFinite(e.lng));if(pts.length){const bounds=L.latLngBounds(pts.map(e=>[e.lat,e.lng]));map.fitBounds(bounds,{padding:[40,40],maxZoom:19})}}
function renderHistoryMap(s){for(const e of Object.values(s.entries||{})){if(!Number.isFinite(e.lat)||!Number.isFinite(e.lng))continue;const m=L.marker([e.lat,e.lng],{icon:spotIcon(e,true),keyboard:false}).addTo(map);m.on('click',ev=>{L.DomEvent.stopPropagation(ev);openSheet('履歴の地点',`<dl class="detail-grid"><dt>場所</dt><dd>${esc(e.address||'地図上の配布地点')}</dd><dt>部数</dt><dd>${e.copies}部</dd><dt>日時</dt><dd>${fmt(s.startedAt)}</dd></dl>`)});state.markers.set(`history:${e.id}`,m)}}
function exitHistory(){state.historySession=null;closeSheet();render()}
$('modeBanner').onclick=exitHistory;
function openSearch(){openSheet('住所検索',`<div class="search-row"><input id="addressQuery" placeholder="住所や建物名を入力"><button id="doSearch">検索</button></div><div id="searchResults" class="result-list"></div>`);$('doSearch').onclick=searchAddress;$('addressQuery').onkeydown=e=>{if(e.key==='Enter')searchAddress()}}
async function searchAddress(){const q=$('addressQuery').value.trim();if(!q)return;$('searchResults').innerHTML='<p class="empty">検索中...</p>';try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=5&countrycodes=jp&q=${encodeURIComponent(q)}`,{headers:{'Accept-Language':'ja'}});const data=await r.json();$('searchResults').innerHTML=data.length?data.map((x,i)=>`<button data-r="${i}">${esc(x.display_name)}</button>`).join(''):'<p class="empty">見つかりませんでした</p>';document.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{const x=data[Number(b.dataset.r)];map.setView([Number(x.lat),Number(x.lon)],19);closeSheet()})}catch{$('searchResults').innerHTML='<p class="empty">検索できませんでした</p>'}}
$('searchFab').onclick=openSearch;
$('locateFab').onclick=()=>{if(!navigator.geolocation){showToast('現在地を取得できません');return}navigator.geolocation.getCurrentPosition(p=>map.setView([p.coords.latitude,p.coords.longitude],19),()=>showToast('位置情報を取得できませんでした'),{enableHighAccuracy:true,timeout:10000})};
render();
